version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp appspec.yml build
      - cd build
      - mkdir scripts
      - cp -R scripts/* build/scripts
artifacts:
  files:
    - build/**/*